CREATE TABLE product(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    measure DECIMAL NOT NULL,
    unit_price DECIMAL NOT NULL,
    arrival date NOT NULL,
    departure date,
    due_date date NOT NULL,
    category varchar(100) NOT NULL
);