spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

